//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enqueue.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationHistory
    {
        public int Id { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ServiceProviderId { get; set; }
        public Nullable<int> Day { get; set; }
        public System.DateTime BookingStartTime { get; set; }
        public Nullable<System.DateTime> BookingEndTime { get; set; }
        public Nullable<System.DateTime> ServiceStartTime { get; set; }
        public Nullable<System.DateTime> ServiceEndTime { get; set; }
        public int ManualTokens { get; set; }
        public int iTokens { get; set; }
        public int iTokensCompleted { get; set; }
        public Nullable<int> iTokensSkip { get; set; }
        public Nullable<int> iTokensNoShow { get; set; }
        public int ManualTokensCompleted { get; set; }
        public Nullable<int> ManualTokensSkip { get; set; }
        public Nullable<int> ManualTokensNoShow { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
