//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enqueue.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.LocationHistories = new HashSet<LocationHistory>();
            this.ServiceProviderOrganizations = new HashSet<ServiceProviderOrganization>();
            this.ServiceProviderServices = new HashSet<ServiceProviderService>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Qualification { get; set; }
        public string RegistrationNo { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> OrganizationId { get; set; }
    
        public virtual ICollection<LocationHistory> LocationHistories { get; set; }
        public virtual ICollection<ServiceProviderOrganization> ServiceProviderOrganizations { get; set; }
        public virtual ICollection<ServiceProviderService> ServiceProviderServices { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
