//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enqueue.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenComment
    {
        public int Id { get; set; }
        public Nullable<int> TokenId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
