//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enqueue.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenStatu
    {
        public TokenStatu()
        {
            this.Tokens = new HashSet<Token>();
        }
    
        public byte Id { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
